[project]
name = "volunteer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["S101", "S311"]
"tests/*.py" = ["S101", "S311"]

dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "ruff>=0.12.10",
]

