name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run ruff check
        run: uv run ruff check --output-format=github .

      - name: Run ruff format check
        run: uv run ruff format --check .

      - name: Run mypy
        run: uv run mypy --strict .

      - name: Run pyrefly
        run: uv run pyrefly check .

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint --format github .

      - name: Run actionlint
        run: |
          # Install actionlint
          url="https://github.com/rhysd/actionlint/releases/latest/download"
          curl -sSL "${url}/actionlint_1.7.4_linux_amd64.tar.gz" | \
            tar -xzf - actionlint
          ./actionlint

      - name: Run pytest with coverage
        run: uv run pytest --cov=. --cov-fail-under=90 --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.11'
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
